name: release-build-tools

on:
  release:
    types:
      - published

env:
  DOCKER_BASE_NAME: ghcr.io/${{ github.repository }}-build-tools

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build . \
            -t "${DOCKER_BASE_NAME}:${GITHUB_SHA::8}" \
            -t "${DOCKER_BASE_NAME}:${{ github.event.release.tag_name }}" \
            -t "${DOCKER_BASE_NAME}:latest"
      - run: docker images

      - name: Push docker image
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push "${DOCKER_BASE_NAME}:${GITHUB_SHA::8}"
          docker push "${DOCKER_BASE_NAME}:${{ github.event.release.tag_name }}"
          docker push "${DOCKER_BASE_NAME}:latest"