name: upload-gh-pages

on:
  push:
    branches:
      - master

jobs:
  upload-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: build-blog
      uses: cssjpn/blog-gh-actions/build-blog@v1

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
